module.exports = {
  USER_TABLE: 'users',
  ROLES_TABLE: 'roles',
  LISTINGS_TABLE: 'listings',
  CITIES_TABLE: 'cities',
  USER_CITYUSER_MAPPING_TABLE: 'User_CityUser_Mapping',
  USER_LISTING_MAPPING_TABLE: 'user_listing_mapping',
  VILLAGE_TABLE: 'village',
  CATEGORIES_TABLE: 'categories',
  STATUS_TABLE: 'status',
  SOURCE_TABLE: 'source',
  SUBCATEGORIES_TABLE: 'subcategory',
  REFRESH_TOKENS_TABLE: 'refreshTokens',
  FORGOT_PASSWORD_TOKENS_TABLE: 'forgot_password_tokens',
  VERIFICATION_TOKENS_TABLE: 'verification_tokens',
  EXCEPTIONS_TABLE: 'exceptions',
  FAVORITES_TABLE: 'FAVORITES',
  CITIZEN_SERVICES_TABLE: 'CITIZEN_SERVICES',
  FORUMS: 'FORUMS',
  FORUMS_POST: 'ForumPosts',
  FORUM_MEMBERS: 'ForumMembers',
  FORUM_REQUEST: 'ForumRequests',
  FORUM_COMMENTS: 'ForumComments',
  POST_REPORTS: 'PostReports',
  FORUM_REQUEST_STATUS:'ForumStatus'
}
