module.exports = {
    USER_TABLE: 'users',
    ROLES_TABLE: 'roles',
    LISTINGS_TABLE: 'listings',
    LISTINGS_IMAGES_TABLE: 'listing_images',
    CITIES_TABLE: 'cities',
    USER_CITYUSER_MAPPING_TABLE: 'user_cityuser_mapping',
    USER_LISTING_MAPPING_TABLE: 'user_listing_mapping',
    VILLAGE_TABLE: 'village',
    CATEGORIES_TABLE: 'categories',
    STATUS_TABLE: 'status',
    SOURCE_TABLE: 'source',
    SUBCATEGORIES_TABLE: 'subcategory',
    REFRESH_TOKENS_TABLE: 'refreshtokens',
    FORGOT_PASSWORD_TOKENS_TABLE: 'forgot_password_tokens',
    VERIFICATION_TOKENS_TABLE: 'verification_tokens',
    EXCEPTIONS_TABLE: 'exceptions',
    FAVORITES_TABLE: 'favorites',
    CITIZEN_SERVICES_TABLE: 'citizen_services',
    MORE_INFO_TABLE: 'moreinfo',
    CITIZEN_SERVICES_DATA_TABLE: 'citizen_service_data',
    FIREBASE_TOKEN: 'firebase_token'
}
